### ISSUE TITLE
Document Enums

### ISSUE THREAD

**Issue by gperdomor** [vapor/docs#357]
Write documentation on how to use the Enums with PostgreSQL and MySQL.

With String enums i was able to make it work in postgres with something like this:

```swift
enum GenderType: String, RawRepresentable, Codable, PostgreSQLRawEnum {
    #if !swift(>=4.2)
    static var allCases: [GenderType] {
        return [.male, .female]
    }
    #endif

    case male
    case female
}
```

and nothing more...

but with `Int`enums, i need something like this:

```swift
enum GenderType: Int, Codable, PostgreSQLEnum, PostgreSQLMigration {
    #if !swift(>=4.2)
    static var allCases: [GenderType] {
        return [.male, .female]
    }
    #endif

    case male = 0
    case female = 1
}
```

and also i need to add the `GenderType ` as migration which is not required by `PostgreSQLRawEnum`... Why this extra step?

I don't know if that step is required in other SQL drivers like MySQL

**Comment by MihaelIsaev** [comment]
@gperdomor 
The right way for defining enum with FluentPostgreSQL
```swift
enum UserRole: String, PostgreSQLEnum, PostgreSQLMigration {
    //remove after swift 4.2 or use #if !swift(>=4.2)
    static let allCases: [UserRole] = [.manager, .supervisor, .admin]
    case manager
    case supervisor
    case admin
}
```
and then in `configure.swift`
```swift
migrations.add(migration: UserRole.self, database: .psql)
```
Native Postgres enums are always strings.
Native Postgres enums registers in the database as custom types, that's why you should create enum in migrations, because Postgres creates separate hidden table for enum values for each enum type inside one database.
Just to clarify, when you create `UserRole` enum, it means that inside a model where you will use it e.g. as `var userRole: UserRole` field Postgres will create `userRole` field with `UserRole` type, not just `text` or `numeric`. And it will work really fast because it's native. As far as I know MySQL doesn't support native enums.
You can read more about enums in Postgres in documentation https://www.postgresql.org/docs/10/static/datatype-enum.html

**Comment by 0xTim** [comment]
These should now be documented for Vapor 4
