### ISSUE TITLE
Support Internationalization

### ISSUE THREAD

**Issue by Mordil** [vapor/docs#401]
It should support right-to-left in addition to left-to-right.

See https://github.com/vapor/website/issues/39

**Comment by tanner0101** [comment]
Looks like MKDocs material supports this: https://squidfunk.github.io/mkdocs-material/getting-started/#text-direction

(Side note, GitHub now supports transferring issues. Should be on the bottom right)

**Comment by cbgrey** [comment]
Is there anything to be done with this issue? (other than needing more translations - which should be separate issues). The LTR concern is addressed automatically by MKDocs as @tanner0101 noted. Should this be closed?

**Comment by tanner0101** [comment]
Yup. For the record, we ended on a separate repo solution. So far we have just english and chinese:

- english: https://github.com/vapor/docs
- chinese: https://github.com/vapor/docs-cn

These are hosted as completely separate projects and domains:

- docs.vapor.codes
- cn.docs.vapor.codes

This makes it easy to work with MKDocs (which doesn't really support multiple languages in a single site) and also keeps the repos separate which is helpful since it gives full control to the respective maintainers that speak the language.
