### ISSUE TITLE
vscode plugin for syntax highlighting

### ISSUE THREAD

**Issue by landsman** [vapor/docs#851]
[It's already there](https://github.com/FranciscoAmado/vscode-html-leaf), unofficial by @FranciscoAmado.
What about some official cooperation? Move it under vapor repository, add note to doc? 🙏 
Without this it's not so much developer friendly I think.

**Comment by 0xTim** [comment]
Transferring to here since this is a documentation problem.

I don't think we have any desire to take over the plugin as a) it's another thing to commit to maintaining and b) we don't want to disparage all the hard work in the linked extension. It should definitely be linked in the docs. @landsman fancy doing a PR?

**Comment by landsman** [comment]
So there isn't exist "official way" for syntax highlight for this template system, ok?

**Comment by 0xTim** [comment]
The official way is to use the extension linked above. That's the one we officially recommend and can help out with if needed
